workspace = { members = ["derive_sml"] }
[package]
name = "small"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitstream-io = "2.2.0"
paste = "1.0.14"
derive_sml = {path = "derive_sml"}


